import http from 'k6/http';
import { check } from 'k6';
import { SharedArray } from 'k6/data';

// Register 200, 201, and 400 as expected non-error statuses globally
http.setResponseCallback(
  http.expectedStatuses({ min: 200, max: 201 }, 400)
);

// 1. Array of seeded account_id UUIDs from your accounts table
const USER_IDS = new SharedArray('users', function () {
  return [
    "user_001",
    "user_002",
    "user_003",
    "user_004",
    "user_005",
    "user_006",
    "user_007",
    "user_008",
    "user_009",
    "user_010",
    "user_011",
    "user_012",
    "user_013",
    "user_014",
    "user_015",
    "user_016",
    "user_017",
    "user_018",
    "user_019",
    "user_020",
    "user_021",
    "user_022",
    "user_023",
    "user_024",
    "user_025",
    "user_026",
    "user_027",
    "user_028",
    "user_029",
    "user_030",
    "user_031",
    "user_032",
    "user_033",
    "user_034",
    "user_035",
    "user_036",
    "user_037",
    "user_038",
    "user_039",
    "user_040",
    "user_041",
    "user_042",
    "user_043",
    "user_044",
    "user_045",
    "user_046",
    "user_047",
    "user_048",
    "user_049",
    "user_050",
    "user_051",
    "user_052",
    "user_053",
    "user_054",
    "user_055",
    "user_056",
    "user_057",
    "user_058",
    "user_059",
    "user_060",
    "user_061",
    "user_062",
    "user_063",
    "user_064",
    "user_065",
    "user_066",
    "user_067",
    "user_068",
    "user_069",
    "user_070",
    "user_071",
    "user_072",
    "user_073",
    "user_074",
    "user_075",
    "user_076",
    "user_077",
    "user_078",
    "user_079",
    "user_080",
    "user_081",
    "user_082",
    "user_083",
    "user_084",
    "user_085",
    "user_086",
    "user_087",
    "user_088",
    "user_089",
    "user_090",
    "user_091",
    "user_092",
    "user_093",
    "user_094",
    "user_095",
    "user_096",
    "user_097",
    "user_098",
    "user_099",
    "user_100",
  ];

});

// Define an array containing the two allowed transaction types for our ledger system
const ENTRY_TYPES = ['DEPOSIT', 'WITHDRAWAL', 'RESERVATION_HOLD', 'RESERVATION_COMMIT'];

// Declare a helper function that constructs a UUID v4 string using pure JavaScript (no npm dependencies needed)
function uuidv4() {
  // Take a standard UUID v4 template string where 'x' and 'y' act as placeholders to be replaced dynamically
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
    // Generate a random integer from 0 to 15 using Bitwise OR (| 0 floors the floating number generated by Math.random)
    const r = (Math.random() * 16) | 0;
    // If the current template character is 'x', use 'r'; if 'y', manipulate bitmask ((r & 0x3) | 0x8) so top bits set variant 1 (RFC 4122)
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    // Convert the single integer (0-15) into its matching hexadecimal character string (0-9, a-f)
    return v.toString(16);
  });
}

// Export the 'options' object so k6 knows how to execute and rate the performance test
export const options = {
  // Define performance test execution scenarios (workload behavior)
  scenarios: {
    // Give a unique name to our target workload scenario
    ledger_transactions: {
      // Use ramping-arrival-rate executor to control Requests Per Second (RPS) independently of target server response latency
      executor: 'ramping-arrival-rate',
      // Start the test generating 50 iterations (requests) per timeUnit
      startRate: 50,
      // Set the base time interval unit for startRate and stages target values to 1 second
      timeUnit: '1s',
      // Pre-allocate 50 Virtual Users (VUs) in memory before the test starts to avoid execution delays
      preAllocatedVUs: 50,
      // Set an upper boundary limit of 200 total Virtual Users k6 can scale up to if response times slow down
      maxVUs: 200,
      // Define how the transaction throughput (RPS) ramps up and ramps down over time
      stages: [
        // Stage 1: Smoothly ramp traffic up from 50 RPS to 200 RPS over 10 seconds
        { duration: '10s', target: 200 },
        // Stage 2: Ramp up further from 200 RPS to a peak load of 500 RPS over 30 seconds
        { duration: '30s', target: 500 },
        // Stage 3: Ramp down traffic cleanly from 500 RPS back to 0 RPS over 10 seconds
        { duration: '10s', target: 0 },
      ],
    },
  },
  // Define pass/fail metrics that determine whether the entire performance test run succeeds or fails
  thresholds: {
    // Less than 1% of total HTTP requests are allowed to return failure HTTP status codes (4xx/5xx)
    http_req_failed: ['rate<0.01'],   // Failing HTTP requests < 1%
    // 95% of all HTTP requests must complete within 50 milliseconds
    http_req_duration: ['p(95)<50'], // 95% of requests under 50ms
  },
};

// Export the default entrypoint function executed continuously by each allocated Virtual User (VU) iteration
export default function () {
  // Pick a single random user_id string out of the pre-loaded global USER_IDS array
  const userId = USER_IDS[Math.floor(Math.random() * USER_IDS.length)];
  // Pick a random entry type ('DEPOSIT' or 'WITHDRAWAL') out of the ENTRY_TYPES array
  const entryType = ENTRY_TYPES[Math.floor(Math.random() * ENTRY_TYPES.length)];

  // Convert the JavaScript object literal into a JSON string format required for the HTTP request body
  const payload = JSON.stringify({
    // Attach the selected target account user_id string
    user_id: userId,
    // Generate a random float amount between 1.00 and 51.00 and format it to 2 decimal places as a string
    amount: (Math.random() * 50 + 1).toFixed(2),
    // Attach the selected entry operation type ('DEPOSIT' or 'WITHDRAWAL')
    entry_type: entryType,
    // Execute helper function to generate a fresh, unique RFC-compliant UUID string for request idempotency
    reference_id: uuidv4() // Generates a valid UUID string
  });

  // Issue an HTTP POST request to the local FastAPI transaction endpoint passing payload data
  const res = http.post('http://localhost:8000/ledger/transaction', payload, {
    // Pass headers specifying that the incoming POST payload body is structured as JSON
    headers: { 'Content-Type': 'application/json' },
  });

  // Evaluate and record check metrics on the HTTP response received from FastAPI
  check(res, {
    // Assert that the response HTTP status code equals 200 OK (returns true/false metric)
    'status is 200': (r) => r.status === 200,
  });
}